### ISSUE TITLE
ownCloud 8.2

### ISSUE THREAD

**Issue by arr0n** [jchaney/owncloud#33]
I'm really new to git, but i thought i's reach out.  I was playing with the dockerfile and used it to deploy a container with for OwnCloud 8.2.0.  I had some issues with the ACPu and gateway timing out when syncing/webdav.  I added these lines;

sed -i 's_listen = /var/run/php5-fpm.sock_listen = 127.0.0.1:9000_' /etc/php5/fpm/pool.d/www.conf
sed -i 's_server unix:/var/run/php5-fpm.sock_ server 127.0.0.1:9000_' /etc/nginx/nginx.conf
sed -i 's!pm.max_children = 50!pm.max_children = 100!' /etc/php5/fpm/pool.d/www.conf
sed -i 's!;pm.max_requests = 500!pm.max_requests = 500!' /etc/php5/fpm/pool.d/www.conf
sed -i 's!pm.start_servers = 2!pm.start_servers = 20!' /etc/php5/fpm/pool.d/www.conf
sed -i 's!pm.min_spare_servers = 1!pm.min_spare_servers = 5!' /etc/php5/fpm/pool.d/www.conf
sed -i 's!pm.max_spare_servers = 3!pm.max_spare_servers = 30!' /etc/php5/fpm/pool.d/www.conf

https://discourse.mailinabox.email/t/consider-listening-on-port-instead-of-socket-for-php5-fpm/434/4
and 
https://github.com/owncloud/core/issues/14187

Just thought i'd pass it along in case you run across it.

Cheers

Arr0n

**Comment by arr0n** [comment]
so with a little more testing, just changing and this "fastcgi_read_timeout 120;" to the nginx.conf(s) files had the desired effect too, in fact it seemed a little better.

**Comment by ypid** [comment]
Thanks! I will look into 8.2 later.

**Comment by ypid** [comment]
Default for `fastcgi_read_timeout` is 60s. http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout

I will test this. Thanks again.

**Comment by arr0n** [comment]
yeah, so in the desktop sync client (and using webdav) when the
default is left it throws timeout errors.  Increasing the timeout to
120 allowed webdav to connect, but still has a few issues with the
desktop-sync client.  My guess (and only from googling the problem)
the issue seems related to acpu.  The php5-fpm error log also moans a
lot about some of the pm settings too.

**Comment by ypid** [comment]
8.2.1 works nicely for me and the people I host it for. The only problem I had was that [CalDAV Sync Adapter](https://f-droid.org/repository/browse/?fdfilter=caldav&fdid=org.gege.caldavsyncadapter) did not work anymore but that seems to be unmaintained anyway so I switched to [DAVdroid](https://f-droid.org/repository/browse/?fdfilter=caldav&fdid=at.bitfire.davdroid) which works nicely.

I will probably merge #34 next weekend. Before then everybody is encuraged to test my [testing branch](https://github.com/ypid/owncloud/tree/own).

Logs are all looking good. @arr0n Do you want to recheck your issue? It is certainly possible that this image is not configured as recommended by ownCloud. In long term I might switch my setup and use this [Ansible role to install and manage my ownCloud instances](https://github.com/debops/ansible-owncloud) see https://github.com/jchaney/owncloud#related-projects and run it in KVM/LXC or something. That will provide better security because the services are way better configured by DebOps.

**Comment by ypid** [comment]
I have no problems so far. Feel free to reopen.
