### ISSUE TITLE
CalDAV/CardDAV/Owncloud client does not work with custom tcp port

### ISSUE THREAD

**Issue by Tobi823** [jchaney/owncloud#41]
For security reason if changed the https port of my OwnCloud instance. After then the Android app DavDroid and the Linux OwnCloud client have some connection issues.

After i changed the port in Makefile line 82 from `--publish $(docker_owncloud_https_port):443 \` to `--publish $(docker_owncloud_https_port):12345 \` and in configs/nginx_ssl.conf line 62 from `listen [::]:443 ssl spdy default_server ipv6only=off;` to `listen [::]:12345 ssl spdy default_server ipv6only=off;` DavDroid and the OwnCloud client finally work.

I did not create a pull request because i have no idea how to manipulate nginx_ssl.conf on the fly. (And sorry for my bad english ;) )

**Comment by ypid** [comment]
I had this usecase in mind. It should be enough to change the `docker_owncloud_https_port` variable https://github.com/jchaney/owncloud/blob/957414a7ae16f375545e6ea25788fc552fd21f8e/Makefile#L6in the Makefile](https://github.com/jchaney/owncloud/blob/957414a7ae16f375545e6ea25788fc552fd21f8e/Makefile#L6). Want to try that?

**Comment by Tobi823** [comment]
Hi ypid,

sorry for my late supply. I still do not have the time to follow your instruction on a clean machine with a clean docker container (but I will do it soon). 

But I am very certain that I have changed the `docker_owncloud_https_port` to 8297 at my first try. I could access my Owncloud with my Firefox on https://10.245.68.4:8297. But DAVdroid on my android device could not access any calendars. I have looked into the error logs and discovered that DAVdroid tries to access some resources on https://10.245.68.4/... . After I changed the port in the nginx_ssl.conf to 8297 DAVdroid works fine. I guess PHP thinks that it runs on 10.245.68.4:443 and thats why PHP generates wrong links (with https://10.245.68.4/... instead of https://10.245.68.4:8297).

**Comment by ypid** [comment]
Hm. It is possible that ownCloud can not always detect to real port being used to access it. This would then be similar to running ownCloud behind a reverse proxy.

So you would need to set the different port in the following places:

* [`docker_owncloud_https_port`](https://github.com/jchaney/owncloud/blob/957414a7ae16f375545e6ea25788fc552fd21f8e/Makefile#L6) so that the Docker container actually listens on that port.
* `'overwritehost' => '10.245.68.4:8297`` in [`$(docker_owncloud_permanent_storage)/config/config.php`](https://github.com/jchaney/owncloud/blob/957414a7ae16f375545e6ea25788fc552fd21f8e/Makefile#L8)
  Refs: https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse%20proxy

You should not need to change the nginx or php settings :wink:

Let me know if it works and feel free to open a PR to make this easier for users.

**Comment by gw0** [comment]
After turning logging in DAVdroid on, I found that a connection to `https://host:port/.well-known/caldav/` gets redirected to `https://host/remote.php/caldav/` (without the port). This is either ownCloud issue that can be overcome with Nginx configuration.

The solution described on DAVdroid page for ownCloud 8 and below (https://davdroid.bitfire.at/configuration/owncloud/) is to enter the direct URL `https://host:port/remote.php/caldav/`. This works!

**Comment by ypid** [comment]
Thanks. Should be possible to fix: https://github.com/jchaney/owncloud/blob/1ea843c3330ebcccb76f1a11fb277977218842c8/configs/nginx.conf#L61-L63

**Comment by gw0** [comment]
I looked a little bit more into it, it seems that the problem is in Nginx that handles the problematic redirection, but does not know the external port being published/port forwarded by Docker (`docker_owncloud_https_port` in Makefile). Nginx thinks it is using port 443 and consequently the following two rules redirect requests there, which fail:

https://github.com/jchaney/owncloud/blob/master/configs/nginx.conf#L84

Nginx documentation about `rewrite` (http://nginx.org/en/docs/http/ngx_http_rewrite_module.html) describes that a full redirect URL is formed according to the request scheme (`$scheme`) and the `server_name_in_redirect` and `port_in_redirect` directives. Because it is not possible to turn this off, the only solution I came up with is to replace all redirects to use the Host field from the HTTP request (that also contains the port, an open question is what happens in browsers that do not specify that field):

```
            rewrite ^/.well-known/carddav $scheme://$http_host/remote.php/carddav/ redirect;
            rewrite ^/.well-known/caldav $scheme://$http_host/remote.php/caldav/ redirect;
```

@ypid I can make a PR for this two lines, but changes elsewhere would need to be verified.

**Comment by ypid** [comment]
@gw0 Sounds good :+1:

> An open question is what happens in browsers that do not specify that [[HTTP_HOST](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields)] field

No real need to worry about that as it is mandatory since HTTP/1.1.

You are welcome to open the PR.
